INCLUDE(${CMAKE_ROOT}/Modules/FindOpenAL.cmake)
IF (NOT OPENAL_FOUND) 
  MESSAGE ("WARNING: Could not find OpenAL - depending targets will be disabled.")
  SET(OE_MISSING_LIBS "${OE_MISSING_LIBS}, OpenAL")
ENDIF (NOT OPENAL_FOUND)